CREATE TABLE POKEMON_INSTANCE
(
    Instance_Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Pokemon_Id  NUMBER NOT NULL,
    Trainer_Id  NUMBER NOT NULL,
    FOREIGN KEY (Pokemon_Id) REFERENCES POKEMON (Pokemon_Id),
    FOREIGN KEY (Trainer_Id) REFERENCES POKEMON_TRAINER (Trainer_Id)

);

COMMIT;